### ISSUE TITLE
多波束原始数据读取

### ISSUE THREAD

**Issue by kjz1997** [AkexStar/MBES-DataProcess-Matlab#1]
你好，作者。我想问一下对于原始的xtf多波束数据，你是如何转为matlab格式的呢？

**Comment by AkexStar** [comment]
@kjz1997 
你好！
很不好意思我不太清楚如何转换不同厂家的原始多波束数据。
但是本项目中的数据[RawData.mat](https://github.com/AkexStar/MBES-DataProcess-Matlab/blob/main/RawData.mat)构成相当简单，每一列是一个单独的变量，你可以参考：

```matlab
>> load("RawData.mat")
>> RawData.Properties

ans = 

  [TableProperties](matlab:helpPopup matlab.tabular.TableProperties) - 属性:

             Description: ''
                UserData: []
          DimensionNames: {'Row'  'Variables'}
           VariableNames: {'pingnum'  'beamnum'  'GNSS_Nm'  'GNSS_Em'  'GNSS_Zm'  'roll'  'pitch'  'heavem'  'heading'  'azimuth'  'angel'  'trans_times'}
    VariableDescriptions: {}
           VariableUnits: {}
      VariableContinuity: []
                RowNames: {}

>> size(RawData)

ans =

      554688          12
```

RawData是一个table，总共有12列、554688行，每一列的变量名在上述信息有显示。意义比较明确。
你可以构造类似的数据结构。

<img width="757" alt="image" src="https://github.com/AkexStar/MBES-DataProcess-Matlab/assets/55226358/ed935f16-0ab7-4f01-b525-646a8ffae6c7">
